TagAuthor/urls.py
from django.urls import path
from TagAuthor import views


app_name="TagAuthor"
urlpatterns = [
    path('',views.home,name="index"),
    path('login/',views.login,name="login"),
    path('logout/',views.logout,name="logout"),
    path('insert/',views.insert,name="insert"),
    path('delete/<int:id>',views.delete,name="delete"),
   
    
   

]

Tags/urls.py
from django.urls import path
from Tags import views

from Tags.views import alltags


app_name="Tags"
urlpatterns = [
    path('allTags/',views.alltags,name="all-Tags-List"),
    path('findtags/',views.findTags,name="find-Tags"),
    path('follow_toggle/',views.followtag,name="follow_toggle"),
 
    # path('write-post/<int:id>/',views.postimages,name="write-post"),

]

XMedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# import xadmin # Temporarily commented out due to NameError in xadmin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MasterEntry.urls')),
    path('user/', include('User.urls')),
    path('posts/', include('Posts.urls')),
    path('tags/', include('Tags.urls')),
    path('tagauthor/', include('TagAuthor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TagAuthor/models.py
from django.db import models

# Create your models here.


class AuthorModel(models.Model):
    a_name = models.CharField(max_length=20,null=False)
    a_pass= models.CharField(max_length=20,null=True)
    a_username=models.CharField(max_length=20,null=True)
    a_loctype=models.CharField(max_length=20,null=True)
    a_location=models.CharField(max_length=50,null=True)
    a_age=models.IntegerField()

    def __str__(self):
        return self.a_name
    

TagAuthor/views.py
from django.shortcuts import get_object_or_404, redirect, render

from django.http import HttpResponse
from .models import AuthorModel
from Tags.models import TagRequest,Tagmodel



# Create your views here.

def home(request):
    if request.session.has_key('authorid'):
        id =  request.session['authorid']
        author=AuthorModel.objects.get(id=id)
        requests = TagRequest.objects.all().order_by('tr_date').reverse()
        # return HttpResponse(author)
        return render(request,"home.html",{'author':author,'request':requests})

    else:
        return redirect("/tagauthor/login")


def login(request):
    if request.session.has_key('authorid'):
        return redirect("/tagauthor")
    else:
        if request.method=="POST":
            userLoged=AuthorModel.objects.filter(a_username=request.POST.get("username"),a_pass=request.POST.get("password")).count()
            if userLoged>0:
                user=get_object_or_404(AuthorModel, a_username=request.POST.get("username"),a_pass=request.POST.get("password"))
                request.session["authorid"]=user.id
                return redirect("/tagauthor")
            else:
                return render(request,"login.html",{'fail':1})
        return render(request,"login.html",{})


def logout(request):
    request.session.flush()
    return redirect("/tagauthor/login")


def delete(request,id):
    TagRequest.objects.get(id=id).delete()
    id =  request.session['authorid']
    author=AuthorModel.objects.get(id=id)
    requests = TagRequest.objects.all()
    return render(request,"home.html",{'author':author,'request':requests , 'flag':1})


def insert(request):
    
    if request.session.has_key('authorid'):

        id =  request.session['authorid']
        author=AuthorModel.objects.get(id=id)
        requests = TagRequest.objects.all()

        if request.method=="POST" and request.FILES:
            t=Tagmodel()
            t.tag_title=request.POST.get("tagtitle")
            t.tag_name=request.POST.get("tagname")
            t.tag_image=request.FILES.get("tagimage")
            t.tag_disc=request.POST.get("tagdesc")
            t.t_country=request.POST.get("tagcountry")
            t.t_state=request.POST.get("tagstate")
            t.t_place=request.POST.get("tagplace")
       
            
            t.save()
            t.tag_image=request.FILES.get("tagimage")
           
            
            return render(request,"home.html",{'author':author,'request':requests , 'add':1})


    else:
        return redirect("/tagauthor/login")

TagAuthor/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>

    <!-- font awsome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />

    <!-- Poppins font -->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700;800;900&display=swap"
      rel="stylesheet"
    />
    <style>
      .login-holder {
        font-family: "Poppins", sans-serif;
        max-width: 400px;
        max-height: 400px;
        width: 100%;
        position: absolute;
        height: 100%;
        box-shadow: 0 0 17px 0 #00000061;
        top: 40%;
        margin-top: -200px;
        margin-left: -200px;
        padding: 10px;
        box-sizing: border-box;
        left: 50%;
      }
      .input-holder {
        margin: 10px;
        text-align: center;
        margin-bottom: 20px;
      }
      .input-holder p {
        margin: 10px auto 0 24px;
        font-size: 12px;
        text-align: left;
      }
      .input-holder input {
        font-size: 14px;
        padding: 12px 15px;
        font-weight: 500;
        border: none;
        background-color: #a9a9a95c;
        border-radius: 5px;
        width: 80%;
      }
      .input-holder input:focus {
        outline-color: darkblue;
      }
      .login-holder .login-button {
        font-family: "Poppins", sans-serif;
        margin: 40px auto;
        padding: 10px 20px;
        border-radius: 7px;
        background-color: #1e7e34;
  border: 1px solid #1e7e34;
        color: white;
        display: block;
        cursor: pointer;
      }
      .login-holder .login-button:hover {
        color: #1e7e34;
background-color: white;
      }
      .login-holder h1 {
        text-align: center;
        margin: 10px auto 40px auto;
      }
       .home-butt{
        color: #0b7dd8;
        position: fixed;
        top: 20px;
        background-color: white;
        text-decoration: none;
        right: 30px;
        box-shadow: 0px 0px 10px 0px #5a5a5a82;
        z-index: 20;
        border-radius: 50px;
        font-size: 12px;
        transition: .3s ease-in-out;
        /* border: 1px solid #d62b0c; */
        padding: 10px 15px;
      }
      .home-butt i{
        font-size: 30px;
    display: block;
    text-align: center;
    padding: 0 5px;
      }
      .home-butt span{
        display: block !important;
        margin: 3px auto 0 auto;
        text-align: center;
      }
      .home-butt:hover{
        color: white;
        text-decoration: none !important;
        background-color: #0b7dd8;
      }
    </style>
  </head>
  <body>
    <a class="home-butt" href="{% url 'TagAuthor:index' %}"><i class="fa fa-home" aria-hidden="true"></i>
      <span>Home</span>
            </a>

{%if fail%}
    <script>
        alert("Wrong username and password.")
    </script>
{%endif%}

    <div class="login-holder">
      <h1>Tag Author Login</h1>
      
      <form action="" method="post">
        {% csrf_token %}
        <div class="input-holder">
          <p>Enter your user name:</p>
          <input type="text" name="username" required placeholder="Username" />
        </div>
        <div class="input-holder">
          <p>Enter your password:</p>
          <input
            type="password"
            name="password"
            required
            placeholder="Password"
          />
        </div>
        <input class="login-button" type="submit" value="Login" />
      </form>
    </div>
  </body>
</html>