Posts/urls.py
from django.urls import path
from Posts import views

from Posts.views import allpost


app_name="Posts"
urlpatterns = [
    path('',views.allpost,name="index"),
    path('post-details/<int:id>/',views.postdetails,name="post-details"),
    path('post-entry/<int:id>/',views.addpost,name="post-entry"),
    # path('post-images/<int:id>',views.postimages,name="post-images"),
    path('related-post/<int:id>',views.relatedpost,name="related-post"),
    path('related-post2/<int:id>',views.relatedpostUser,name="related-post-user"),
    path('post-vote/<int:id>',views.postvote,name="post-vote"),
    path('addcomment/<int:id>',views.addcomment,name="addcomment"),
    path('pos-vote/',views.posvote,name="pos-vote"),
    path('neg-vote/',views.negvote,name="neg-vote"),


]

Tags/urls.py
from django.urls import path
from Tags import views

from Tags.views import alltags


app_name="Tags"
urlpatterns = [
    path('allTags/',views.alltags,name="all-Tags-List"),
    path('findtags/',views.findTags,name="find-Tags"),
    path('follow_toggle/',views.followtag,name="follow_toggle"),
 
    # path('write-post/<int:id>/',views.postimages,name="write-post"),

]

XMedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# import xadmin # Temporarily commented out due to NameError in xadmin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MasterEntry.urls')),
    path('user/', include('User.urls')),
    path('posts/', include('Posts.urls')),
    path('tags/', include('Tags.urls')),
    path('tagauthor/', include('TagAuthor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Tags/models.py
from django.db import models
from User.models import UserModel


# Create your models here.
class Tagmodel(models.Model):
    tag_title=models.CharField(max_length=40,default=0)
    tag_name=models.CharField(max_length=40,unique=True)
    tag_image=models.ImageField(upload_to='tags')
    tag_disc=models.TextField(default=0)
    t_country=models.CharField(max_length=20)
    t_state=models.CharField(max_length=20)
    t_place=models.CharField(max_length=20)

    

    def __str__(self):
        return self.tag_name+" "+self.t_country+" "+self.t_state+" "+self.t_place

class TagRequest(models.Model):
    tr_title=models.CharField(max_length=40,default=0)
    tr_type=models.CharField(max_length=10,default=0)
    tr_content=models.TextField(default=0)
    tr_c=models.CharField(max_length=40,default=0)
    tr_s=models.CharField(max_length=40,default=0)
    tr_p=models.CharField(max_length=40,default=0)
    tr_date =models.DateTimeField(auto_now=True,null=False)
    user_id=models.ForeignKey(UserModel,on_delete=models.SET_NULL,null=True,verbose_name="user")

    def __str__(self):
        return self.tr_title+" - "+self.tr_c+" - "+self.tr_s+" - "+self.tr_p
    


class following(models.Model):
    tag = models.ForeignKey(Tagmodel,on_delete=models.SET_NULL,null=True,verbose_name="Tagmodel")
    user = models.ForeignKey(UserModel,on_delete=models.SET_NULL,null=True,verbose_name="UserModel")
    is_follow = models.BooleanField(default=0)
    follow_count = models.IntegerField(default=0)

    def __str__(self):
        return str(self.tag) 

Tags/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from .models import Tagmodel, following
from django.db.models import Count , F
from Posts.models import PostModel
from User.models import UserModel
import json

# Create your views here.


def alltags(request):
    if request.session.has_key('userid'):
        user=UserModel.objects.get(id=request.session['userid'])
        ctags=Tagmodel.objects.filter(t_country__iexact=user.u_country)
        stags=Tagmodel.objects.filter(t_state__iexact=user.u_state)

        # Use u_selected_nearby_city if available, otherwise fallback to u_detected_city
        if user.u_selected_nearby_city:
            ptags = Tagmodel.objects.filter(t_place__iexact=user.u_selected_nearby_city)
        elif user.u_detected_city:
            ptags = Tagmodel.objects.filter(t_place__iexact=user.u_detected_city)
        else:
            ptags = Tagmodel.objects.none() # No place information available

        return render(request, "alltags.html",{'ctags':ctags ,'stags':stags ,'ptags':ptags , 'user':user})
       
    else:
        return redirect("/user/login")

def findTags(request):
    if request.session.has_key('userid'):
        loggeduser = UserModel.objects.get(id = request.session['userid'])
        tags = Tagmodel.objects.all()
        users_tag = following.objects.filter(user = loggeduser)
        followed_tags_ids = [f.tag.id for f in users_tag] # Get IDs of tags the user follows
        country = PostModel.objects.all().values('tag_id__t_country').annotate(dcount=Count('tag_id__t_country')).order_by()
        # user-tags = PostModel.objects.all().values('user_id__t_country').annotate(gcount=Count('tag_id__t_country')).order_by()
        users = UserModel.objects.all()

        # return HttpResponse(mytag)
        return render(request, "find-tags.html",{
            'users':users,
            "tags":tags,
            "country":country,
            "u_tags":users_tag,
            "followed_tags_ids": followed_tags_ids, # Pass the list of followed tag IDs
        })

    else:
        return redirect("/user/login")


def followtag(request):
    if not request.session.has_key('userid'):
        return JsonResponse({'success': False, 'message': 'User not logged in.'}) # Return JSON for AJAX

    if request.method == "POST":
        try:
            tag_id = request.POST.get('tag_id')
            if not tag_id:
                return JsonResponse({'success': False, 'message': 'Tag ID is required.'})
            
            tag = get_object_or_404(Tagmodel, id=tag_id)
            user = UserModel.objects.get(id=request.session['userid'])
            is_followed = False

            if following.objects.filter(tag=tag, user=user).exists():
                # Unfollow
                current_fol = following.objects.filter(tag=tag).count()
                following.objects.filter(tag=tag).update(follow_count=F("follow_count") - 1)
                following.objects.get(tag=tag, user=user).delete()
                message = 'Tag unfollowed.'
                is_followed = False
            else:
                # Follow
                foll = following(tag=tag, user=user, is_follow=1)
                foll.save()
                current_fol = following.objects.filter(tag=tag).count()
                following.objects.filter(tag=tag).update(follow_count=F("follow_count") + 1)
                message = 'Tag followed.'
                is_followed = True

            return JsonResponse({'success': True, 'message': message, 'is_followed': is_followed})
        except Exception as e:
            return JsonResponse({'success': False, 'message': str(e)}) # Return specific error message
    else:
        return JsonResponse({'success': False, 'message': 'Invalid request method.'})

Tags/templates/alltags.html
{% extends 'base.html' %}
{% block title %}X-media | Tags{% endblock %}

    {% block content %}
    <style>
      .navbar-nav #tags{
        color: white !important;
       
    
      }
    </style>
    <a class="tag-request" href="/user/tag-req">
      Tag <br> request
    </a>
    <div class="all-tag-holder">
    {% comment %} country {% endcomment %}
      
      <div class="dtag-holder">
        <p class="dtag-title">Tags related to your country <span>{{user.u_country}}:</span></p>
        {% if ctags %}
        {% for ctag in ctags%}
        
        <a href="{% url 'Posts:post-vote' ctag.id %}">
          <div class="tag">
            <p class="tag-name">{{ctag.tag_name}}</p>
            <p class="tag-title">{{ctag.tag_title}}</p>
            <p class="tag-desc"><span>Description:</span>{{ctag.tag_disc}}</p>
            <img
              class="tag-image"
              src="{{ctag.tag_image.url}}"
              alt="tagimage"
              srcset=""
            />
            <div class="place-holder">
            <div class="places"><span>Country:</span>{{ctag.t_country}}</div>
              
  
            </div>
            
          </div>
          <a href="{% url 'Posts:post-entry' ctag.id %}" class="add-tag-butt">
            <i class="fa fa-pencil" aria-hidden="true"></i><span> ADD POST</span>
          </a>
          <hr>
          </a>
          {%endfor%}
          {% else %}
      <h3 class="tag-error">No tags</h3>
      {% endif %}
        
        
      </div>
      
      
      


    {% comment %} state {% endcomment %}

    <div class="dtag-holder">
      <p class="dtag-title">Tags related to your state <span>{{user.u_state}}:</span></p>
      {% if stags %}

      {% for stag in stags%}
      

      <a href="{% url 'Posts:post-vote' stag.id %}">
      <div class="tag">
        <p class="tag-name">{{stag.tag_name}}</p>
        <p class="tag-title">{{stag.tag_title}}</p>
        <p class="tag-desc"><span>Description:</span>{{stag.tag_disc}}</p>
        <img
          class="tag-image"
          src="{{stag.tag_image.url}}"
          alt="tagimage"
          srcset=""
        />
        <div class="place-holder">
          {% comment %} <div class="places"><span>Country:</span>{{stag.t_country}}</div> {% endcomment %}
          <div class="places"><span>State:</span>{{stag.t_state}}</div>
          {% comment %} <div class="places"><span>Place:</span>{{stag.t_place}}</div> {% endcomment %}
        </div>
      </div>
      <a href="{% url 'Posts:post-entry' stag.id %}" class="add-tag-butt">
        <i class="fa fa-plus" aria-hidden="true"></i><span> ADD POST</span>
      </a>
      <hr>
      </a>
      {%endfor%}

      {% else %}
      <h3 class="tag-error">No tags</h3>
      {% endif %}
</div>



    {% comment %} place {% endcomment %}
    <div class="dtag-holder">
      <p class="dtag-title">Tags related to your place <span>{{user.u_place}}:</span></p>
      {% if ptags  %}
       {% for stag in ptags%}
      <a href="{% url 'Posts:post-vote' stag.id %}">
      <div class="tag">
        <p class="tag-name">{{stag.tag_name}}</p>
        <p class="tag-title">{{stag.tag_title}}</p>
        <p class="tag-desc"><span>Description:</span>{{stag.tag_disc}}</p>
        <img
          class="tag-image"
          src="{{stag.tag_image.url}}"
          alt="tagimage"
          srcset=""
        />
        <div class="place-holder">
 
          
          <div class="places"><span>Place:</span>{{stag.t_place}}</div>
        </div>
      </div>
      <a href="{% url 'Posts:post-entry' stag.id %}" class="add-tag-butt">
        <i class="fa fa-plus" aria-hidden="true"></i><span> ADD POST</span>
      </a>
      <hr>
      </a>
      {%endfor%}
      
      {% else %}
      <h3 class="tag-error">No tags</h3>
      {% endif %}
     
</div>

    </div>
    </div>

  {% endblock content %}

Tags/templates/find-tags.html
{% extends 'base.html' %} {% block title %}X-media | Find{% endblock %}
{% block content %}
<style>
  .navbar-nav #find {
    color: white !important;
  }
   .tag-place-dat{
    position: absolute;
    top: 3px;
    right: 10px;
    font-size: 20px;
  }
  .tag-place-dat i{
    padding-right: 5px;
  }
  .the-tag{
    z-index: 1;
        width: 87%;
        border:2px solid #212121;
    position: relative;
    transition: .3s ease;
    top: 0;
  }
  .tag-place-dat i{
    padding-right: 7px;
  }
  .the-tag:hover{
    border:2px solid white;
  }
  .the-tag-head h2,
  .the-tag-head span{
    font-size: 35px;
  }
  .post-count p{
    font-size: 11px;
  }
  .post-count{
    font-size: 25px;
    bottom: 5px;
  }
  .tag-cov-img{
    width: 100%;
  }
  .tag-place-dat{
    font-size: 15px;
    top: 5px;
  }
  .tag-error{
    margin: 40px auto;
  }
</style>

<div class="search-holder">
  <input
    type="text"
    id="searchinput"
    onkeyup="search()"
    placeholder="Search for tags, countries or users"
    id="search"
  />

  <ul id="searchlist" class="search-cls">
      <!-- country -->
      {% if country %} {% for post in country %}
      {% if not post.tag_id__t_country == "0" %}
      <li>
          <div style="background: #d31a1a;" class="serch-icon">
              <i class="fa fa-map-marker" aria-hidden="true"></i>
          </div>
        <p style="text-transform: capitalize;">{{ post.tag_id__t_country}}</p>
        <p class="post-cc" >{{ post.dcount}}</p>
        <p class="cc-custom" >Posts</p>
        
        <!-- <img
         
          src="{{user.u_pic.url}}"
          alt="user-dp"
          srcset=""
        /> -->
      </li>
      {% endif %}
      {% endfor %} {% endif %}


      <!-- tags -->
    {% if tags %} {% for tag in tags %}
    <a href="{% url 'Posts:related-post' tag.id %}">
    
    <li>
        <div  style="background: #3F51B5;" class="serch-icon">
            <i class="fa fa-tag"  aria-hidden="true"></i>
        </div>
      <p style="text-transform: uppercase;">#{{ tag.tag_name }}</p>
      <p style="font-size: 14px;
      text-align: center;
      position: absolute;
      top: 30px;
      line-height: 0;"><i class="fa fa-map-marker" aria-hidden="true"></i> 
      
{{ tag.t_country|default:'' }}{% if tag.t_country and tag.t_state %}, {% endif %}{{ tag.t_state|default:'' }}{% if tag.t_state and tag.t_place %}, {% endif %}{{ tag.t_place|default:'' }}

      </p>
      <img
       
        src="{{tag.tag_image.url}}"
        alt="tag-image"
        srcset=""
      />
    </li>
    </a>
    {% endfor %} {% endif %}


    <!-- user -->
    {% if user %} {% for user in users %}
    <a href="{% url 'Posts:related-post-user' user.id %}">
    <li>
        <div style="background: #009688;" class="serch-icon">
            <i class="fa fa-user" aria-hidden="true"></i>
        </div>
      <p style="text-transform: capitalize;">{{ user.u_name }}</p>
      <img
       
        src="{{user.u_pic.url}}"
        alt="user-dp"
        srcset=""
      />
    </li>
  </a>
    {% endfor %} {% endif %}
  
  </ul>

</div>

<div id="tags-table-container" style="margin-top: 20px; padding: 15px; background-color: #2E2E2E; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);">
  <h4 style="color: white; margin-bottom: 15px;">All Created Tags</h4>
  <table style="width: 100%; border-collapse: collapse; color: white; text-align: left;">
    <thead>
      <tr style="background-color: #3C3C3C;">
        <th style="padding: 10px; border: 1px solid #4A4A4A;">Tag Name</th>
        <th style="padding: 10px; border: 1px solid #4A4A4A;">Country</th>
        <th style="padding: 10px; border: 1px solid #4A4A4A;">State</th>
        <th style="padding: 10px; border: 1px solid #4A4A4A;">Place</th>
        <th style="padding: 10px; border: 1px solid #4A4A4A;">Action</th>
      </tr>
    </thead>
    <tbody>
      {% if tags %}
        {% for tag in tags %}
          <tr style="border-bottom: 1px solid #4A4A4A;">
            <td style="padding: 10px; border: 1px solid #4A4A4A;">{{ tag.tag_name }}</td>
            <td style="padding: 10px; border: 1px solid #4A4A4A;">{{ tag.t_country|default:'' }}</td>
            <td style="padding: 10px; border: 1px solid #4A4A4A;">{{ tag.t_state|default:'' }}</td>
            <td style="padding: 10px; border: 1px solid #4A4A4A;">{{ tag.t_place|default:'' }}</td>
            <td style="padding: 10px; border: 1px solid #4A4A4A;">
              <button class="follow-toggle-button" data-tag-id="{{ tag.id }}" style="background: none; border: none; cursor: pointer; color: #4CAF50; font-size: 1.2em;">
                {% if tag.id in followed_tags_ids %}
                  <i class="fa fa-times-circle" aria-hidden="true" style="color: #f44336;"></i>
                {% else %}
                  <i class="fa fa-plus-circle" aria-hidden="true"></i>
                {% endif %}
              </button>
            </td>
          </tr>
        {% endfor %}
      {% else %}
        <tr>
          <td colspan="5" style="padding: 10px; text-align: center; color: #888;">No tags created yet.</td>
        </tr>
      {% endif %}
    </tbody>
  </table>
</div>

{% if u_tags %}
<!-- followings tags -->
<h4 class="u-follow-title" id="folltitle">Tags You Follow</h4>
<div class="u-follow-holder">
<div class="row">
  
   
    {% for tag in u_tags  %}
    <div class="col-sm-6">
      <a href="{% url 'Posts:related-post' tag.tag.id %}">
    <div class="the-tag d-flex">
     <div style="background-image: url('{{tag.tag.tag_image.url }}');" class="tag-cov-img">
      <div class="the-tag-head">
        <h2><span>#</span>{{tag.tag.tag_name}} 
        </h2>
  
      </div>
  
      <!-- tag location -->
      {% if tag.tag.t_country != "0" %}
  
      <p class="tag-place-dat">
        <i class="fa fa-map-marker" aria-hidden="true"></i>
        {{tag.tag.t_country}}
      </p>
      {% endif %}
  
  
  
      {% if tag.tag.t_state != "0" %}
  
      <p class="tag-place-dat">
        <i class="fa fa-map-marker" aria-hidden="true"></i>
        {{tag.tag.t_state}}
      </p>
      {% endif %}
  
  
  
      {% if tag.tag.t_place != "0" %}
      <p class="tag-place-dat">
        <i class="fa fa-map-marker" aria-hidden="true"></i>
        {{tag.tag.t_place}}
      </p>
      {% endif %}
  
    <div style="right: 10px;" class="post-count">
      {{tag.follow_count}} <p>Followers</p>
    </div>
   
     
     </div>
     
  </div>
  </a>
    </div>
    {% endfor %}
    
   
</div>
 
  
</div>
{% else %}
    <h3 class="tag-error">No tags</h3>
{% endif %}


<script>
  // Existing search function
  function search() {
    var input, filter, ul, li, a, i;
    input = document.getElementById("searchinput");
    filter = input.value.toUpperCase();
    ul = document.getElementById("searchlist");
    title = document.getElementById("folltitle"); // This might need adjustment if you remove the title conditionally
    li = ul.getElementsByTagName("li");

    if (input.value.length == 0) {
      ul.style.display = "none";
      if (title) title.style.opacity = "1"; // Only try to set opacity if title exists
      return;
    } else {
      ul.style.display = "block";
      if (title) title.style.opacity = "0"; // Only try to set opacity if title exists
    }
    // Loop through all list items, and hide those who don't match the search query
    for (i = 0; i < li.length; i++) {
      a = li[i].getElementsByTagName("p")[0];
      if (a.innerHTML.toUpperCase().indexOf(filter) > -1) {
        li[i].style.display = "block";
      } else {
        li[i].style.display = "none";
      }
    }
  }

  // New JavaScript for follow/unfollow button
  $(document).ready(function() {
    $('.follow-toggle-button').on('click', function(e) {
      e.preventDefault(); // Prevent default link behavior if button is inside an <a>
      const button = $(this);
      const tagId = button.data('tag-id');
      const csrfToken = $('input[name=csrfmiddlewaretoken]').val();

      $.ajax({
        url: '{% url "Tags:follow_toggle" %}', // This URL needs to be defined in Tags/urls.py
        type: 'POST',
        data: {
          'tag_id': tagId,
          'csrfmiddlewaretoken': csrfToken,
        },
        success: function(response) {
          if (response.success) {
            if (response.is_followed) {
              button.html('<i class="fa fa-times-circle" aria-hidden="true" style="color: #f44336;"></i>');
              // Optionally update follower count or refresh part of the page
            } else {
              button.html('<i class="fa fa-plus-circle" aria-hidden="true"></i>');
              // Optionally update follower count or refresh part of the page
            }
            alert(response.message); // Show a success message
          } else {
            alert('Error: ' + response.message);
          }
        },
        error: function(xhr, status, error) {
          console.error('AJAX Error:', status, error);
          alert('An error occurred. Please try again.');
        }
      });
    });
  });
</script>

{% endblock content %}